services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=acme'
      - 'POSTGRES_USER=acme_user'
      - 'POSTGRES_PASSWORD=acme_password'
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rabbitmq:3.9.29-management-alpine'
    environment:
      - 'RABBITMQ_DEFAULT_USER=acme_user'
      - 'RABBITMQ_DEFAULT_PASS=acme_password'
    ports:
      - '5672:5672'
      - '15672:15672'