services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=acme'
      - 'POSTGRES_USER=acme_user'
      - 'POSTGRES_PASSWORD=acme_password'
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rabbitmq:3.9.29-management-alpine'
    environment:
      - 'RABBITMQ_DEFAULT_USER=acme_user'
      - 'RABBITMQ_DEFAULT_PASS=acme_password'
    ports:
      - '5672:5672'
      - '15672:15672'
  mockServer:
    image: mockserver/mockserver:5.14.0
    ports:
      - 3000:1080
    environment:
      MOCKSERVER_WATCH_INITIALIZATION_JSON: "true"
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializationJson.json
    volumes:
      - ./mockserver/initializationJson.json:/config/initializationJson.json